version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data